CREATE TABLE appropriations (
	SubmittingAgencyId INT,
	PackageSubmissionDate date,
	ReportingPeriod varchar(10),
	TreasuryAccountSymbolEntryID INT,
	ApportionmentCategoryA varchar(50),
	ApportionmentCategoryB varchar(50),
	ApportionmentCategoryAB varchar(50),
	ApportionmentCategoryE varchar(50),
	TreasuryAccountSymbolCommonRenderingLabel varchar(50),
	AllocationTransferRecipientAgencyId INT NULL,
	AppropriationAccountResponsibleAgencyId INT,
	ObligationUnlimitedAvailabilityPeriodIndicator varchar(50),
	ObligationAvailabilityPeriodStartFiscalYear INT,
	ObligationAvailabilityPeriodStartDate date,
	ObligationAvailabilityPeriodEndFiscalYear INT,
	ObligationAvailabilityPeriodEndDate date,
	AppropriationMainAccountCode INT,
	AppropriationSubAccountCode INT,
	AppropriationAccountExpiredStatus boolean,
	BudgetAuthorityAvailableAmountTotal decimal(15,2),
	BudgetAuthorityUnobligatedAmountPriorYearCarryover decimal(15,2),
	BudgetAuthorityAppropriatedAmountTotal decimal(15,2),
	OtherBudgetaryResourcesAmountTotal decimal(15,2),
	ContractAuthorityAmountTotal decimal(15,2),
	BorrowingAuthorityAmountTotal decimal(15,2),
	SpendingAuthorityFromOffsettingCollectionsAmountTotal decimal(15,2),
	BudgetAuthorityAdjustmentsTotal decimal(15,2),
	AvailableForObligationAmountTotal decimal(15,2),
	ObligationsIncurredTotal decimal(15,2),
	ObligationsAmountTotal decimal(15,2),
	OutlaysAmountTotal decimal(15,2),
	UnobligatedAmountTotal decimal(15,2)
);